"""
Numerical/symbolic verification for Lemma 1 (Simplex invariant and curvature bound)
in supervised_study/draft/theory.tex.

Run:  py supervised_study/proofs/lemma1.py
Output: supervised_study/proofs/lemma1.md

WHAT THIS DOES AND DOES NOT DO
------------------------------
This script checks that the *specific inequalities and constants* claimed in the
proof hold, and are tight where the paper says they are tight. It is a guard
against arithmetic/spectral-norm errors, not a theorem prover: it confirms the
claims at sampled / witnessed points and via the symbolic variance-identity step,
but it
does not replace the analytic argument for all d.

CLAIM (Lemma 1)
    L_LSE(d) = -log sum_j exp(-d_j),  r = softmax(-d)
    grad_d L_LSE = r  (on the simplex)
    Hessian:  rr^T - diag(r);  negative Hessian C(r) = diag(r) - rr^T >= 0
    ||C(r)||_2 = ||Hessian||_2 <= 1/2,  tight at r = (1/2, 1/2, 0, ..., 0).
"""

import numpy as np
import sympy as sp

RNG = np.random.default_rng(0)
LINES = []


def log(s=""):
    print(s)
    LINES.append(s)


def softmax_neg(d):
    e = np.exp(-d - (-d).max())
    return e / e.sum()


def check_gradient_is_r():
    """grad_d L_LSE = r, verified against finite differences."""
    ok = True
    worst = 0.0
    for K in (3, 8, 25):
        d = RNG.standard_normal(K)
        r = softmax_neg(d)

        def L(dd):
            return -np.log(np.exp(-dd).sum())

        eps = 1e-6
        num = np.array(
            [(L(d + eps * np.eye(K)[i]) - L(d - eps * np.eye(K)[i])) / (2 * eps)
             for i in range(K)]
        )
        err = np.abs(num - r).max()
        worst = max(worst, err)
        ok &= err < 1e-6
        ok &= abs(r.sum() - 1.0) < 1e-12 and (r >= 0).all()
    return ok, worst


def check_hessian_form():
    """Hessian = rr^T - diag(r); C(r) = diag(r) - rr^T is PSD."""
    ok = True
    worst = 0.0
    for K in (4, 10, 25):
        d = RNG.standard_normal(K)
        r = softmax_neg(d)
        H_claim = np.outer(r, r) - np.diag(r)

        def L(dd):
            return -np.log(np.exp(-dd).sum())

        eps = 1e-4

        def g(dd):
            return np.array(
                [(L(dd + eps * np.eye(K)[i]) - L(dd - eps * np.eye(K)[i])) / (2 * eps)
                 for i in range(K)]
            )

        Hn = np.array(
            [(g(d + eps * np.eye(K)[i]) - g(d - eps * np.eye(K)[i])) / (2 * eps)
             for i in range(K)]
        )
        Hn = (Hn + Hn.T) / 2
        err = np.abs(H_claim - Hn).max()
        worst = max(worst, err)
        ok &= err < 1e-4
        C = np.diag(r) - np.outer(r, r)
        ok &= np.linalg.eigvalsh(C).min() > -1e-10  # PSD
    return ok, worst


def check_half_bound():
    """||C(r)||_2 <= 1/2, tight at the two-point distribution."""
    ok = True
    worst_max = 0.0
    for K in (2, 3, 10, 25):
        best = 0.0
        for _ in range(20000):
            r = RNG.dirichlet(np.ones(K))
            C = np.diag(r) - np.outer(r, r)
            best = max(best, np.linalg.norm(C, 2))
        ok &= best <= 0.5 + 1e-9
        worst_max = max(worst_max, best)
    # tightness: two-point (1/2, 1/2)
    r2 = np.array([0.5, 0.5])
    tight = np.linalg.norm(np.diag(r2) - np.outer(r2, r2), 2)
    ok &= abs(tight - 0.5) < 1e-12
    return ok, worst_max, tight


def check_popoviciu_symbolic():
    """Symbolic: v^T C(r) v = Var_{j~r}(v_j) and the range-squared <= 2 for unit v."""
    r1, r2, v1, v2 = sp.symbols('r1 r2 v1 v2', real=True)
    r = sp.Matrix([r1, r2, 1 - r1 - r2])
    v = sp.Matrix([v1, v2, 0])
    C = sp.diag(*r) - r * r.T
    quad = sp.simplify((v.T * C * v)[0])
    var = sp.simplify(sum(r[i] * v[i] ** 2 for i in range(3))
                      - (sum(r[i] * v[i] for i in range(3))) ** 2)
    return sp.simplify(quad - var) == 0


def main():
    log("# Lemma 1 -- Simplex Invariant and Curvature Bound")
    log()
    log("Verification of `theory.tex`, Lemma `lem:simplex`. "
        "Generated by `proofs/lemma1.py`.")
    log()

    ok_g, err_g = check_gradient_is_r()
    log(f"- **grad_d L_LSE = r**: analytic vs finite-difference max error "
        f"`{err_g:.2e}`; sums to 1, nonnegative. **{'PASS' if ok_g else 'FAIL'}**")

    ok_h, err_h = check_hessian_form()
    log(f"- **Hessian = rr^T - diag(r)**, C(r) PSD: max error `{err_h:.2e}`. "
        f"**{'PASS' if ok_h else 'FAIL'}**")

    ok_b, worst, tight = check_half_bound()
    log(f"- **||C(r)||_2 <= 1/2**: max over 20k samples per K in "
        f"{{2,3,10,25}} is `{worst:.5f}`; two-point value `{tight:.5f}` "
        f"(tight). **{'PASS' if ok_b else 'FAIL'}**")

    ok_p = check_popoviciu_symbolic()
    log(f"- **Variance identity (symbolic)**: v^T C(r) v = Var_(j~r)(v_j) "
        f"confirmed identically for a representative K=3 symbolic simplex "
        f"parameterization. **{'PASS' if ok_p else 'FAIL'}**")

    log()
    all_ok = ok_g and ok_h and ok_b and ok_p
    log(f"**Overall: {'ALL CHECKS PASS' if all_ok else 'FAILURE -- see above'}.**")
    log()
    log("_Scope: confirms the claimed identities/constants at sampled and "
        "witnessed points and via the symbolic variance identity; not a "
        "general-d theorem prover._")

    with open(__file__.replace('.py', '.md'), 'w', encoding='utf-8') as f:
        f.write("\n".join(LINES) + "\n")
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
