"""
Verification for Proposition 1 (Conditioning under private affine energies) in
supervised_study/draft/theory.tex.

Run:  py supervised_study/proofs/prop1.py
Output: supervised_study/proofs/prop1.md

CLAIM (Proposition 1)
    Private affine energies d_j = w_j^T x + b_j, xt = (x, 1), d_j = theta_j^T xt.
    Gradient block for component j is r_j * xt, hence
        ||grad_theta L_LSE||_2 = sqrt(sum_j r_j^2) * ||xt|| <= ||xt||.
    Hessian = C(r) (x) (xt xt^T)  (Kronecker), up to sign, so
        ||Hessian_theta L_LSE||_2 = ||C(r)||_2 * ||xt||^2 <= (1/2) ||xt||^2,
    a constant fixed by the data, independent of theta.

SCOPE: checks the analytic gradient/Hessian forms against finite differences and
the resulting spectral-norm bounds at sampled points. Not a general proof.
"""

import numpy as np

RNG = np.random.default_rng(1)
LINES = []


def log(s=""):
    print(s)
    LINES.append(s)


def softmax_neg(d):
    e = np.exp(-d - (-d).max())
    return e / e.sum()


def setup(K, n):
    x = RNG.standard_normal(n)
    xt = np.append(x, 1.0)
    W = RNG.standard_normal((K, n))
    b = RNG.standard_normal(K)
    theta = np.concatenate([np.append(W[j], b[j]) for j in range(K)])
    d = W @ x + b
    return x, xt, W, b, theta, d, K, n


def L_factory(x, K, n):
    def L(th):
        th = th.reshape(K, n + 1)
        dd = th[:, :n] @ x + th[:, n]
        return -np.log(np.exp(-dd).sum())
    return L


def check_gradient():
    ok = True
    worst_err = 0.0
    worst_ratio = 0.0
    for K, n in [(4, 6), (10, 20), (25, 50)]:
        x, xt, W, b, theta, d, K, n = setup(K, n)
        r = softmax_neg(d)
        grad = np.concatenate([r[j] * xt for j in range(K)])  # analytic
        L = L_factory(x, K, n)
        m = len(theta)
        eps = 1e-6
        num = np.array(
            [(L(theta + eps * np.eye(m)[i]) - L(theta - eps * np.eye(m)[i])) / (2 * eps)
             for i in range(m)]
        )
        err = np.abs(grad - num).max()
        gnorm = np.linalg.norm(grad)
        bound = np.sqrt(xt @ xt)
        worst_err = max(worst_err, err)
        worst_ratio = max(worst_ratio, gnorm / bound)
        ok &= err < 1e-6 and gnorm <= bound + 1e-9
    return ok, worst_err, worst_ratio


def check_hessian():
    ok = True
    worst_err = 0.0
    worst_ratio = 0.0
    for K, n in [(4, 5), (10, 8)]:
        x, xt, W, b, theta, d, K, n = setup(K, n)
        r = softmax_neg(d)
        C = np.diag(r) - np.outer(r, r)
        H_kron = np.kron(C, np.outer(xt, xt))      # claimed, up to sign
        L = L_factory(x, K, n)
        m = len(theta)
        eps = 1e-4

        def g(th):
            return np.array(
                [(L(th + eps * np.eye(m)[i]) - L(th - eps * np.eye(m)[i])) / (2 * eps)
                 for i in range(m)]
            )

        Hn = np.array(
            [(g(theta + eps * np.eye(m)[i]) - g(theta - eps * np.eye(m)[i])) / (2 * eps)
             for i in range(m)]
        )
        Hn = (Hn + Hn.T) / 2
        err = min(np.abs(H_kron - Hn).max(), np.abs(-H_kron - Hn).max())
        num_norm = np.linalg.norm(Hn, 2)
        bound = 0.5 * (xt @ xt)
        worst_err = max(worst_err, err)
        worst_ratio = max(worst_ratio, num_norm / bound)
        ok &= err < 1e-4 and num_norm <= bound + 1e-5
    return ok, worst_err, worst_ratio


def main():
    log("# Proposition 1 -- Conditioning under Private Affine Energies")
    log()
    log("Verification of `theory.tex`, Proposition `prop:private-affine`. "
        "Generated by `proofs/prop1.py`.")
    log()

    ok_g, eg, rg = check_gradient()
    log(f"- **Gradient block = r_j * xt**, `||grad|| <= ||xt||`: analytic vs "
        f"finite-difference max error `{eg:.2e}`; worst norm/bound ratio "
        f"`{rg:.3f}` (<= 1). **{'PASS' if ok_g else 'FAIL'}**")

    ok_h, eh, rh = check_hessian()
    log(f"- **Hessian = C(r) (x) xt xt^T (Kronecker)**, "
        f"`||H|| <= (1/2)||xt||^2`: form matches numeric Hessian to `{eh:.2e}`; "
        f"worst norm/bound ratio `{rh:.3f}` (<= 1). **{'PASS' if ok_h else 'FAIL'}**")

    log()
    log("The Kronecker-product spectral-norm step "
        "`||A (x) B||_2 = ||A||_2 ||B||_2` is what turns Lemma 1's `1/2` and "
        "`||xt||^2` into the parameter-independent constant `(1/2) E||xt||^2` "
        "under batch-mean training.")
    log()
    all_ok = ok_g and ok_h
    log(f"**Overall: {'ALL CHECKS PASS' if all_ok else 'FAILURE -- see above'}.**")
    log()
    log("_Scope: confirms the analytic gradient/Hessian forms and the resulting "
        "bounds at sampled points; not a general-parameter theorem prover._")

    with open(__file__.replace('.py', '.md'), 'w', encoding='utf-8') as f:
        f.write("\n".join(LINES) + "\n")
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
